# Site settings
title: the500 challenge
description: Listening to one of 500 best albums of all times
keywords: rolling stones 500 challenge
author: Wojciech Krysmann
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://the500.kryss.blog" # the base hostname & protocol for your site
